/** Fallback project data used when MongoDB is not available */
export const fallbackProjects = [
  {
    _id: '1',
    title: 'Customer Purchase Behavior Analyzer',
    slug: 'customer-purchase-analyzer',
    description:
      'Data mining system analyzing 5,000+ retail transactions across 8 Ghanaian cities using K-Means clustering, Apriori algorithm, and predictive models (Decision Tree, Random Forest, Logistic Regression).',
    longDescription: '',
    tags: ['Python', 'Scikit-learn', 'Pandas', 'Matplotlib'],
    category: 'data',
    image: '',
    liveUrl: '#',
    githubUrl: 'https://github.com/Pro-Clergy/customer-purchase-analyzer',
    featured: true,
    order: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '2',
    title: 'E-Commerce Platform',
    slug: 'e-commerce-platform',
    description:
      'Full-stack online store with user authentication, product catalog, shopping cart, Stripe payment integration, and a responsive admin dashboard.',
    longDescription: '',
    tags: ['React', 'Node.js', 'MongoDB', 'Stripe'],
    category: 'web',
    image: '',
    liveUrl: '#',
    githubUrl: 'https://github.com/Pro-Clergy/e-commerce-platform',
    featured: true,
    order: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '3',
    title: 'Task Management Dashboard',
    slug: 'task-management-dashboard',
    description:
      'Collaborative project management tool with real-time updates, drag-and-drop Kanban boards, team assignments, and performance analytics.',
    longDescription: '',
    tags: ['Next.js', 'Tailwind', 'PostgreSQL', 'Socket.io'],
    category: 'web',
    image: '',
    liveUrl: '#',
    githubUrl: 'https://github.com/Pro-Clergy/task-management-dashboard',
    featured: true,
    order: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '4',
    title: 'AI Chatbot for Customer Support',
    slug: 'ai-chatbot-customer-support',
    description:
      'Intelligent conversational AI with NLP capabilities, trained on domain-specific data to handle customer inquiries and automate support workflows.',
    longDescription: '',
    tags: ['Python', 'Flask', 'TensorFlow', 'REST API'],
    category: 'ai',
    image: '',
    liveUrl: '#',
    githubUrl: 'https://github.com/Pro-Clergy/ai-chatbot-customer-support',
    featured: true,
    order: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
